grail_save_folder = "D:/CAREN Resources/Data"
movement_names = {
    "kinematics": {
        "sagittal": [
            {"fr": "Tronc gauche", "en": "Rotation TrunkFlex"},
            {"fr": "Tronc droit", "en": "Rotation TrunkFlex"},
            {"fr": "Bassin gauche", "en": "Rotation PelvicTil"},
            {"fr": "Bassin droit", "en": "Rotation PelvicTil"},
            {"fr": "Hanche gauche", "en": "Rotation LHipFlex"},
            {"fr": "Hanche droite", "en": "Rotation RHipFlex"},
            {"fr": "Genou gauche", "en": "Rotation LKneeFlex"},
            {"fr": "Genou droit", "en": "Rotation RKneeFlex"},
            {"fr": "Cheville gauche", "en": "Rotation LAnkleFlex"},
            {"fr": "Cheville droite", "en": "Rotation RAnkleFlex"},
        ],
        "frontal": [
            {"fr": "Tronc gauche", "en": "Rotation TrunkTilt"},
            {"fr": "Tronc droit", "en": "Rotation TrunkTilt"},
            {"fr": "Bassin gauche", "en": "Rotation PelvicObl"},
            {"fr": "Bassin droit", "en": "Rotation PelvicObl"},
            {"fr": "Hanche gauche", "en": "Rotation LHipAbAd"},
            {"fr": "Hanche droite", "en": "Rotation RHipAbAd"},
            {"fr": "Genou gauche", "en": "Rotation LKneeAbAd"},
            {"fr": "Genou droit", "en": "Rotation RKneeAbAd"},
        ],
        "transversal": [
            {"fr": "Tronc gauche", "en": "Rotation TrunkRot"},
            {"fr": "Tronc droit", "en": "Rotation TrunkRot"},
            {"fr": "Bassin gauche", "en": "Rotation PelvicRot"},
            {"fr": "Bassin droit", "en": "Rotation PelvicRot"},
            {"fr": "Hanche gauche", "en": "Rotation LHipRot"},
            {"fr": "Hanche droite", "en": "Rotation RHipRot"},
            {"fr": "Genou gauche", "en": "Rotation LKneeRot"},
            {"fr": "Genou droit", "en": "Rotation RKneeRot"},
            {"fr": "Progression du pied gauche", "en": "LProgression"},
            {"fr": "Progression du pied droit", "en": "RProgression"},
        ],
    },
    "moment": {
        "sagittal": [
            {"fr": "Hanche gauche", "en": "Moment LHipFlex"},
            {"fr": "Hanche droite", "en": "Moment RHipFlex"},
            {"fr": "Genou gauche", "en": "Moment LKneeFlex"},
            {"fr": "Genou droit", "en": "Moment RKneeFlex"},
            {"fr": "Cheville gauche", "en": "Moment LAnkleFlex"},
            {"fr": "Cheville droite", "en": "Moment RAnkleFlex"},
        ],
        "frontal": [
            {"fr": "Hanche gauche", "en": "Moment LHipAbAd"},
            {"fr": "Hanche droite", "en": "Moment RHipAbAd"},
            {"fr": "Genou gauche", "en": "Moment LKneeAbAd"},
            {"fr": "Genou droit", "en": "Moment RKneeAbAd"},
            {"fr": "Cheville gauche", "en": "Moment LAnkleAbAd"},
            {"fr": "Cheville droite", "en": "Moment RAnkleAbAd"},
        ],
        "transversal": [
            {"fr": "Hanche gauche", "en": "Moment LHipRot"},
            {"fr": "Hanche droite", "en": "Moment RHipRot"},
            {"fr": "Genou gauche", "en": "Moment LKneeRot"},
            {"fr": "Genou droit", "en": "Moment RKneeRot"},
            {"fr": "Cheville gauche", "en": "Moment LAnkleRot"},
            {"fr": "Cheville droite", "en": "Moment RAnkleRot"},
        ],
    },
    "power": {
        "sagittal": [
            {"fr": "Hanche gauche", "en": "Power LHipFlex"},
            {"fr": "Hanche droite", "en": "Power RHipFlex"},
            {"fr": "Genou gauche", "en": "Power LKneeFlex"},
            {"fr": "Genou droit", "en": "Power RKneeFlex"},
            {"fr": "Cheville gauche", "en": "Power LAnkleFlex"},
            {"fr": "Cheville droite", "en": "Power RAnkleFlex"},
        ],
        "frontal": [
            {"fr": "Hanche gauche", "en": "Power LHipAbAd"},
            {"fr": "Hanche droite", "en": "Power RHipAbAd"},
            {"fr": "Genou gauche", "en": "Power LKneeAbAd"},
            {"fr": "Genou droit", "en": "Power RKneeAbAd"},
            {"fr": "Cheville gauche", "en": "Power LAnkleAbAd"},
            {"fr": "Cheville droite", "en": "Power RAnkleAbAd"},
        ],
        "transversal": [
            {"fr": "Hanche gauche", "en": "Power LHipRot"},
            {"fr": "Hanche droite", "en": "Power RHipRot"},
            {"fr": "Genou gauche", "en": "Power LKneeRot"},
            {"fr": "Genou droit", "en": "Power RKneeRot"},
            {"fr": "Cheville gauche", "en": "Power LAnkleRot"},
            {"fr": "Cheville droite", "en": "Power RAnkleRot"},
        ],
    },
}
